"""
Pydantic schemas for LLM input/output and API request/response models.

These models define the structured contract between:
  - The end-user API  (PromptRequest)
  - The LLM response  (PlaylistResponse / SuggestedTrack)
  - Sync status       (SyncStatus)
"""

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# LLM I/O schemas
# ---------------------------------------------------------------------------


class SuggestedTrack(BaseModel):
    """A single track suggested by the LLM.

    Attributes:
        title:     Track title as it appears in the Plex library.
        artist:    Artist name as it appears in the Plex library.
        album:     Album name (optional).
        reasoning: Brief explanation of why this track was chosen.
    """

    title: str = Field(..., description="Track title as it appears in the Plex library.")
    artist: str = Field(..., description="Artist name as it appears in the Plex library.")
    album: Optional[str] = Field(None, description="Album name (optional).")
    reasoning: str = Field(..., description="Brief explanation of why this track was chosen.")

    @field_validator("title", "artist", mode="before")
    @classmethod
    def strip_whitespace(cls, v: str) -> str:
        return v.strip() if isinstance(v, str) else v


class PlaylistResponse(BaseModel):
    """A complete playlist generated by the LLM.

    Attributes:
        name:        Human-readable playlist name.
        description: Short description of the playlist's vibe/theme.
        tracks:      Ordered list of suggested tracks.
    """

    name: str = Field(..., description="Human-readable playlist name.")
    description: str = Field(..., description="Short description of the playlist's vibe/theme.")
    tracks: List[SuggestedTrack] = Field(
        default_factory=list,
        description="Ordered list of suggested tracks.",
    )


# ---------------------------------------------------------------------------
# API request schemas
# ---------------------------------------------------------------------------


class PromptRequest(BaseModel):
    """User-supplied natural-language prompt for playlist generation.

    Attributes:
        prompt:      Natural-language description of the desired playlist.
        track_count: Requested number of tracks (default 20, max 100).
    """

    prompt: str = Field(
        ...,
        min_length=3,
        max_length=1000,
        description="Natural-language description of the desired playlist.",
    )
    track_count: int = Field(
        default=20,
        ge=1,
        le=100,
        description="Requested number of tracks (1-100).",
    )


# ---------------------------------------------------------------------------
# Sync status schema
# ---------------------------------------------------------------------------


class SyncStatus(BaseModel):
    """Current state of the library metadata sync operation.

    Attributes:
        synced_tracks: Number of tracks successfully synced so far.
        total_tracks:  Total tracks found in the Plex library (0 if unknown).
        last_synced_at: ISO-8601 timestamp of the last completed sync, or None.
        in_progress:   True while a sync job is actively running.
    """

    synced_tracks: int = Field(default=0, ge=0)
    total_tracks: int = Field(default=0, ge=0)
    last_synced_at: Optional[datetime] = Field(default=None)
    in_progress: bool = Field(default=False)


# ---------------------------------------------------------------------------
# Phase 5: Semantic Bridge schemas
# ---------------------------------------------------------------------------


class PlaylistIntent(BaseModel):
    """Structured intent extracted from user prompt via Ollama (Gemma).

    Attributes:
        mood:        Desired emotional vibe (e.g., "relaxed", "energetic").
        tempo:       Tempo preference (e.g., "slow", "medium", "fast").
        genre_hint:  Primary genre preference (optional, e.g., "jazz").
        exclude:     List of terms to exclude from results (e.g., ["christmas"]).
    """

    mood: str = Field(..., description="Desired emotional vibe.")
    tempo: str = Field(..., description="Tempo preference (slow/medium/fast).")
    genre_hint: str = Field(
        default="",
        description="Primary genre preference (optional).",
    )
    exclude: List[str] = Field(
        default_factory=list,
        description="Terms to exclude from results.",
    )


class SeedSelection(BaseModel):
    """Indices of tracks selected as sonic seeds by Gemma.

    Attributes:
        indices: 1-based positions of chosen tracks in the candidate list.
    """

    indices: List[int] = Field(
        ...,
        description="1-based indices of selected tracks (e.g., [1, 3]).",
    )
