"""
SQLAlchemy ORM table definitions.

Defines the persistent data model for the library metadata cache.
"""

from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from app.models.database import Base


class Track(Base):
    """Cached representation of a Plex music library track.

    Stores essential metadata extracted during library sync so that
    the prompt processor can query the local catalogue without
    hitting the Plex server on every request.
    """

    __tablename__ = "tracks"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    rating_key: Mapped[int] = mapped_column(Integer, unique=True, nullable=False, index=True)
    title: Mapped[str] = mapped_column(String, nullable=False)
    artist: Mapped[str] = mapped_column(String, nullable=False)
    album: Mapped[str | None] = mapped_column(String, nullable=True)
    genre: Mapped[str | None] = mapped_column(String, nullable=True)
    style: Mapped[str | None] = mapped_column(String, nullable=True)
    has_sonic_analysis: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    synced_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    def __repr__(self) -> str:
        return (
            f"<Track(id={self.id}, rating_key={self.rating_key}, "
            f"title={self.title!r}, artist={self.artist!r})>"
        )


class TrackVector(Base):
    """Vector embedding for a track (Phase 5: Semantic Bridge).

    Stores dense vector embeddings generated by sentence-transformers
    for semantic similarity search. One vector per track.
    """

    __tablename__ = "track_vectors"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    track_id: Mapped[int] = mapped_column(Integer, nullable=False, index=True)
    embedding: Mapped[bytes] = mapped_column(nullable=False)  # Binary float32 array
    model_name: Mapped[str] = mapped_column(String, nullable=False)  # e.g., "all-MiniLM-L6-v2"
    dimension: Mapped[int] = mapped_column(Integer, nullable=False)  # e.g., 384
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    def __repr__(self) -> str:
        return (
            f"<TrackVector(id={self.id}, track_id={self.track_id}, "
            f"dimension={self.dimension}, model={self.model_name})>"
        )
