"""
Suggest API endpoint.

POST /api/suggest — Accept a natural-language prompt and return a
                    PlaylistResponse generated by the LLM.
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.database import get_session
from app.models.schemas import PlaylistResponse, PromptRequest
from app.services.ollama_client import OllamaError, generate_playlist
from app.services.prompt_processor import (
    build_prompt,
    extract_keywords,
    parse_intent,
)
from app.trace import get_trace_id

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/suggest", tags=["Suggest"])


@router.post(
    "",
    response_model=PlaylistResponse,
    status_code=status.HTTP_200_OK,
    summary="Generate playlist from natural-language prompt",
)
async def suggest_playlist(
    request: PromptRequest,
    session: AsyncSession = Depends(get_session),
) -> PlaylistResponse:
    """Generate a playlist using the LLM based on a natural-language prompt.

    Pipeline:
    1. Extract keywords from the prompt.
    2. Build a context pool from the local library cache.
    3. Construct a system prompt with library context.
    4. Call Ollama with retry + over-request logic.
    5. Return the structured PlaylistResponse.

    **Example request:**
    ```json
    {"prompt": "upbeat 90s rock", "track_count": 20}
    ```

    **Error responses:**
    - 503 — Ollama service is unavailable.
    - 422 — Invalid request body (validation error).
    """
    trace_id = get_trace_id()
    logger.info(
        "POST /api/suggest | trace_id=%s | prompt=%r | track_count=%d",
        trace_id,
        request.prompt,
        request.track_count,
    )

    try:
        # Parse intent to detect genre hints, mood, etc.
        logger.info("Parsing intent from prompt: %r", request.prompt)
        intent = await parse_intent(request.prompt)
        logger.info(
            "Parsed intent: genre_hint=%r, mood=%r, tempo=%r, exclude=%s",
            intent.genre_hint,
            intent.mood,
            intent.tempo,
            intent.exclude,
        )
        
        # Extract keywords from the prompt
        search_terms = extract_keywords(request.prompt)
        logger.info("Extracted search terms: %s", search_terms)
        
        # Build prompt with search terms and intent
        system_prompt, user_message = await build_prompt(
            session, request.prompt, search_terms, request.track_count, intent=intent
        )
    except Exception as exc:
        logger.exception("Failed to build prompt.")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to build prompt: {exc}",
        ) from exc

    try:
        playlist = await generate_playlist(system_prompt, user_message, request.track_count)
    except OllamaError as exc:
        logger.error("Ollama error: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        ) from exc
    except Exception as exc:
        logger.exception("Unexpected error during playlist generation.")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Playlist generation failed: {exc}",
        ) from exc

    if not playlist.tracks:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=(
                "The LLM returned an empty playlist. "
                "Try a different prompt or sync your library first."
            ),
        )

    logger.info(
        "Returning playlist '%s' with %d tracks | trace_id=%s",
        playlist.name,
        len(playlist.tracks),
        trace_id,
    )
    return playlist
